platform :ios, '16.0'

target 'NewsConsolidator' do
  use_frameworks!

  pod 'Texture', '~> 3.2'
  pod 'RealmSwift', '~> 10.54'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
